- name: Deploy ArgoCD
  hosts: localhost
  connection: local

  tasks:
    - name: Deploy ArgoCD
      community.kubernetes.helm:
        release_name: argocd
        chart_repo_url: https://argoproj.github.io/argo-helm
        chart_ref: argo-cd
        release_namespace: "{{ argocd_namespace }}"
        create_namespace: true
        release_values:
          configs:
            repositories:
             gitops-repo:
               url: https://github.com/ishanjainn/gitops
               username: "{{ vault_github_username }}"
               password: "{{ vault_github_user_password }}"
          server:
            additionalApplications:
               - name: main-app
                 namespace: argocd
                 project: default
                 source:
                   repoURL: https://github.com/ishanjainn/gitops
                   path: argocd/releases/beta/
                   targetRevision: HEAD
                   directory:
                     recurse: true
                 destination:
                   server: https://kubernetes.default.svc
                   namespace: argocd
                 syncPolicy:
                   automated:
                     prune: true
                     selfHeal: true
